"""Add Topic model

Revision ID: 17b19ad637f5
Revises: 8fd0aa64bd90
Create Date: 2024-10-20 16:38:38.911889

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17b19ad637f5'
down_revision = '8fd0aa64bd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exam_type', sa.Enum('TOEFL', 'IELTS', name='examtype'), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_category'), 'topic', ['category'], unique=False)
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=False)
    op.create_index(op.f('ix_topic_question'), 'topic', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_question'), table_name='topic')
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_category'), table_name='topic')
    op.drop_table('topic')
    # ### end Alembic commands ###
