"""Change topics id to uuid

Revision ID: 1cbf8d935f05
Revises: cdec8acde33f
Create Date: 2024-10-20 23:27:14.156746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cbf8d935f05'
down_revision = 'cdec8acde33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
