"""Add submission_evaluations_v2 Table

Revision ID: 3326dd722f2e
Revises: f3c16385856e
Create Date: 2024-11-14 23:15:14.972018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3326dd722f2e'
down_revision = 'f3c16385856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_evaluations_v2',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submission_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('evaluation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['topic_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_evaluations_v2_id'), 'submission_evaluations_v2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_evaluations_v2_id'), table_name='submission_evaluations_v2')
    op.drop_table('submission_evaluations_v2')
    # ### end Alembic commands ###
