"""Add metadata field to column

Revision ID: df5ed3dc846d
Revises: 1cbf8d935f05
Create Date: 2024-10-20 23:37:30.476714

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'df5ed3dc846d'
down_revision = '1cbf8d935f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('topic_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'topic_metadata')
    # ### end Alembic commands ###
